name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true
jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  build:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Install test/lint dependencies
        run: pip install pytest pylint

      - name: Run linter
        run: pylint plover_q_and_a

      - name: Run tests
        run: pytest
