name: PyPI release
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  # Adapted from: https://github.com/pypa/gh-action-pypi-publish#usage
  pypi-publish:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
    name: Build, Lint, Test, Release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/plover-q-and-a/
    permissions:
      id-token: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install test/lint dependencies
        run: pip install pytest pylint

      - name: Run linter
        run: pylint plover_q_and_a

      - name: Run tests
        run: pytest

      - name: Install build
        run: python -m pip install --upgrade build

      - name: Build
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
