name: Create Release
on:
  push:
    tags:
      - "v*"
jobs:
  # Adapted from: https://github.com/pypa/gh-action-pypi-publish#usage
  pypi-publish:
    name: Build, Lint, Test, Release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/plover-q-and-a/
    permissions:
      id-token: write
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Test, Lint, Type Checking Dependencies
        run: pip install pytest pylint mypy coverage

      - name: Run Linter
        run: pylint plover_q_and_a

      - name: Run Type Checker
        run: mypy plover_q_and_a

      - name: Run Tests
        run: pytest

      - name: Run Coverage
        run: |
          coverage run --module pytest
          coverage report --show-missing

      - name: Install Build
        run: python -m pip install --upgrade build

      - name: Build
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Release pushed tag on GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$TAG" \
            --generate-notes

